image:
- Visual Studio 2015
- Visual Studio 2017
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    
install:
- ps: Get-Command cmake
